### ISSUE TITLE
Oppdatere til scram-sha-256

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-mongodb-config#17]
- [ ] Oppdatere til scram-sha-256 auth mechanism
- [ ] Oppdatere secrets/variabler som refererer til den gamle

**Comment by KjerstiSteien** [comment]
@valosnah prioritet?

**Comment by valosnah** [comment]
Lukker denne, da det er bedre å få flyttet applikasjoner over til mongodb-clusteret
